# Site settings
title: "Sansad: APIs for the Parliament of India"
#email: lokeshk@sansad.co
description: > # this means to ignore newlines until "baseurl:"
  Sansad provides you the latest data from the Parliament of India. Call
  the APIs to know what your local legislator is up to, or where that
  bill on education is stuck. It's more information, and thus, more power
  to you!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sansad.co" # the base hostname & protocol for your site
twitter_username: lokeshku
github_username:  KumarL

# Build settings
markdown: kramdown
